services:
  - type: web
    name: wikidata-mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python minimal_server.py
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
